# Generated by Django 3.2.6 on 2021-08-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210811_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address_line',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
